# Generated by Django 4.2.20 on 2025-12-23 22:46

import budget.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('account_type', models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings'), ('credit', 'Credit Card'), ('cash', 'Cash'), ('other', 'Other')], default='checking', max_length=20)),
                ('last4', models.CharField(blank=True, max_length=4)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('mapping_override', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('mapping', models.JSONField(blank=True, null=True)),
                ('mapping_version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.FileField(upload_to=budget.models.statement_upload_to)),
                ('source_type', models.CharField(choices=[('csv', 'CSV'), ('pdf', 'PDF')], default='csv', max_length=8)),
                ('file_hash', models.CharField(db_index=True, max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('statement_start_date', models.DateField(blank=True, null=True)),
                ('statement_end_date', models.DateField(blank=True, null=True)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('mapping_version_used', models.PositiveIntegerField(default=1)),
                ('parsed_ok', models.BooleanField(default=False)),
                ('parse_error', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statements', to='budget.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='account',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='budget.bank'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('raw_reference', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='budget.account')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='budget.bankstatement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transaction_date', '-id'],
                'indexes': [models.Index(fields=['user', 'transaction_date'], name='budget_tran_user_id_3ff094_idx'), models.Index(fields=['account', 'transaction_date'], name='budget_tran_account_1ddac6_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='bankstatement',
            constraint=models.UniqueConstraint(fields=('user', 'account', 'file_hash'), name='uniq_statement_user_account_hash'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('user', 'bank', 'name'), name='uniq_account_user_bank_name'),
        ),
    ]
